export * from "./Login";
export * from "./Landing";
export * from "./Register";
export * from "./Dashboard";
export * from "./Profile";
export * from "./Header";
export * from "./Project";
export * from "./Faq";
export * from "./ThirdPartyLogin";